### ISSUE TITLE
[BUG]  Cant change verstion to older

### ISSUE THREAD

**Issue by fatyzzz** [marzneshin/marzneshin#785]
### Current Behavior

I try to change marzneshin verstion from 0.7.0 to 0.6.4
and i see the bug
marzneshin-1  | INFO  [alembic.runtime.migration] Context impl MariaDBImpl.
marzneshin-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzneshin-1  | FAILED: Can't locate revision identified by '57eba0a293f2'
marzneshin-1  | ERROR [alembic.util.messaging] Can't locate revision identified by '57eba0a293f2'
marzneshin-1 exited with code 255
marzneshin-1  | INFO  [alembic.runtime.migration] Context impl MariaDBImpl.
marzneshin-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzneshin-1  | FAILED: Can't locate revision identified by '57eba0a293f2'
marzneshin-1  | ERROR [alembic.util.messaging] Can't locate revision identified by '57eba0a293f2'
marzneshin-1 exited with code 255
marzneshin-1  | INFO  [alembic.runtime.migration] Context impl MariaDBImpl.
marzneshin-1  | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
marzneshin-1  | ERROR [alembic.util.messaging] Can't locate revision identified by '57eba0a293f2'
marzneshin-1  | FAILED: Can't locate revision identified by '57eba0a293f2'
marzneshin-1 exited with code 255

### Environment

OS: Debian 12

Browsers: nothing

Version: 0.7.0

**Comment by fatyzzz** [comment]
```
services:
  marzneshin:
    image: dawsh/marzneshin:v0.6.4
    restart: always
    env_file: .env
    environment:
      SQLALCHEMY_DATABASE_URL: "mariadb+pymysql://root:12341234@127.0.0.1/marzneshin"
    network_mode: host
    volumes:
      - /var/lib/marzneshin:/var/lib/marzneshin
    depends_on:
      db:
        condition: service_healthy
        required: true
  marznode:
    image: dawsh/marznode:latest
    restart: always
    network_mode: host
    environment:
      SERVICE_ADDRESS: "127.0.0.1"
      INSECURE: "True"
      XRAY_EXECUTABLE_PATH: "/usr/local/bin/xray"
      XRAY_ASSETS_PATH: "/usr/local/lib/xray"
      XRAY_CONFIG_PATH: "/var/lib/marznode/xray_config.json"
      SSL_KEY_FILE: "./server.key"
      SSL_CERT_FILE: "./server.cert"
    volumes:
      - /var/lib/marznode:/var/lib/marznode
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 12341234
      MARIADB_DATABASE: marzneshin
    volumes:
      - /var/lib/marzneshin/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: healthcheck.sh --connect
      interval: 5s
      retries: 4
```
